import { CatalogSettings, Category, ProductWithDetails, CatalogPageWithProducts } from '../types/database.types';

export const INITIAL_SETTINGS: CatalogSettings = {
  id: 'sett-001',
  brand_name: 'PRESTIGE',
  brand_subtitle: 'MODA DE LUJO',
  hero_title: 'NUEVOS LOOKS / NUEVA ACTITUD',
  hero_description: 'Descubre las últimas tendencias y renueva tu estilo con prendas creadas para destacar.',
  season_label: 'NUEVA TEMPORADA',
  hero_image_url: '/img/portada.png',
  logo_url: null,
  whatsapp_url: 'https://wa.me/573000000000?text=Hola%20PRESTIGE,%20estoy%20interesado%20en%20consultar%20el%20cat%C3%A1logo',
  instagram_url: 'https://instagram.com/prestigecol.online',
  tiktok_url: 'https://tiktok.com/@prestigecol.online',
  website_url: 'https://www.prestigecol.online',
  primary_color: '#111111',
  accent_color: '#E6D19A',
  is_published: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-01',
    name: 'Camisetas Oversize',
    slug: 'camisetas-oversize',
    description: 'Corte amplio y estructurado en algodón pesado de primera calidad.',
    image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80',
    sort_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-02',
    name: 'Hoodies & Sweaters',
    slug: 'hoodies-sweaters',
    description: 'Básicos elevados y hoodies de textura pesada para abrigo urbano.',
    image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=600&q=80',
    sort_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-03',
    name: 'Chaquetas',
    slug: 'chaquetas',
    description: 'Outwear refinado para complementar el look streetwear de lujo.',
    image_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=600&q=80',
    sort_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-04',
    name: 'Pantalones Cargo & Joggers',
    slug: 'pantalones-cargo-joggers',
    description: 'Siluetas relajadas con acabados técnicos y máxima comodidad.',
    image_url: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=600&q=80',
    sort_order: 4,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-05',
    name: 'Gorras & Accesorios',
    slug: 'gorras-accesorios',
    description: 'Detalles exclusivos de marca que completan tu presencia.',
    image_url: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=600&q=80',
    sort_order: 5,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_PRODUCTS: ProductWithDetails[] = [
  {
    id: 'prod-01',
    category_id: 'cat-01',
    category: INITIAL_CATEGORIES[0],
    name: 'Camiseta Oversize Core Black',
    slug: 'camiseta-oversize-core-black',
    sku: 'PR-TS001',
    short_description: 'Camiseta premium de corte relajado, algodón pesado 240g con caída impecable.',
    description: 'Fabricada en algodón 100% peruano peinado de 240 gramos. Cuello acanalado reforzado de 3cm, hombros caídos y costuras invisibles. Una prenda esencial urbana de lujo con durabilidad garantizada.',
    price: 79900,
    compare_at_price: 99900,
    currency: 'COP',
    badge: 'NUEVO',
    is_active: true,
    is_featured: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: 'img-01-1',
        product_id: 'prod-01',
        image_url: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=800&q=80',
        alt_text: 'Camiseta Oversize Core Black frente',
        sort_order: 1,
        is_primary: true,
        created_at: new Date().toISOString(),
      },
      {
        id: 'img-01-2',
        product_id: 'prod-01',
        image_url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80',
        alt_text: 'Camiseta Oversize Core Black detalle',
        sort_order: 2,
        is_primary: false,
        created_at: new Date().toISOString(),
      }
    ],
    variants: [
      { id: 'v-01-1', product_id: 'prod-01', color_name: 'Negro Core', color_hex: '#111111', size: 'S', stock: 10, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { id: 'v-01-2', product_id: 'prod-01', color_name: 'Negro Core', color_hex: '#111111', size: 'M', stock: 15, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { id: 'v-01-3', product_id: 'prod-01', color_name: 'Negro Core', color_hex: '#111111', size: 'L', stock: 8, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { id: 'v-01-4', product_id: 'prod-01', color_name: 'Negro Core', color_hex: '#111111', size: 'XL', stock: 5, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { id: 'v-01-5', product_id: 'prod-01', color_name: 'Blanco Óptico', color_hex: '#FFFFFF', size: 'M', stock: 12, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { id: 'v-01-6', product_id: 'prod-01', color_name: 'Gris Grafito', color_hex: '#333333', size: 'L', stock: 0, is_available: false, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    ]
  },
  {
    id: 'prod-02',
    category_id: 'cat-02',
    category: INITIAL_CATEGORIES[1],
    name: 'Hoodie Essential Graphite',
    slug: 'hoodie-essential-graphite',
    sku: 'PR-H001',
    short_description: 'Hoodie premium de corte relajado, algodón franelado pesado y capota de doble capa.',
    description: 'Construido en mezcla de algodón 400g franelado ultra suave al tacto. Bolsillo canguro frontal con remaches reforzados, puños rib acanalados y ajuste estructurado. Diseñado para ofrecer confort y estilo sofisticado.',
    price: 159900,
    compare_at_price: 189900,
    currency: 'COP',
    badge: 'EDICIÓN LIMITADA',
    is_active: true,
    is_featured: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: 'img-02-1',
        product_id: 'prod-02',
        image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
        alt_text: 'Hoodie Essential Graphite',
        sort_order: 1,
        is_primary: true,
        created_at: new Date().toISOString(),
      }
    ],
    variants: [
      { id: 'v-02-1', product_id: 'prod-02', color_name: 'Grafito', color_hex: '#2B2B2B', size: 'S', stock: 5, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { id: 'v-02-2', product_id: 'prod-02', color_name: 'Grafito', color_hex: '#2B2B2B', size: 'M', stock: 10, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { id: 'v-02-3', product_id: 'prod-02', color_name: 'Beige Champagne', color_hex: '#E6D19A', size: 'L', stock: 6, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { id: 'v-02-4', product_id: 'prod-02', color_name: 'Negro Matte', color_hex: '#111111', size: 'XL', stock: 0, is_available: false, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    ]
  },
  {
    id: 'prod-03',
    category_id: 'cat-04',
    category: INITIAL_CATEGORIES[3],
    name: 'Cargo Relaxed Olive',
    slug: 'cargo-relaxed-olive',
    sku: 'PR-CG001',
    short_description: 'Pantalón cargo de tiro medio, múltiples bolsillos tácticos y silueta relajada.',
    description: 'Pantalón tipo cargo confeccionado en dril ripstop de alta resistencia. Cuenta con 6 bolsillos utilitarios con broches dorados grabados con el monograma PRESTIGE y botas ajustables.',
    price: 149900,
    compare_at_price: null,
    currency: 'COP',
    badge: 'NUEVO',
    is_active: true,
    is_featured: true,
    sort_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: 'img-03-1',
        product_id: 'prod-03',
        image_url: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=800&q=80',
        alt_text: 'Cargo Relaxed Olive',
        sort_order: 1,
        is_primary: true,
        created_at: new Date().toISOString(),
      }
    ],
    variants: [
      { id: 'v-03-1', product_id: 'prod-03', color_name: 'Oliva Militar', color_hex: '#4B5320', size: '30', stock: 4, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { id: 'v-03-2', product_id: 'prod-03', color_name: 'Oliva Militar', color_hex: '#4B5320', size: '32', stock: 8, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { id: 'v-03-3', product_id: 'prod-03', color_name: 'Oliva Militar', color_hex: '#4B5320', size: '34', stock: 6, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { id: 'v-03-4', product_id: 'prod-03', color_name: 'Negro Urbano', color_hex: '#111111', size: '36', stock: 3, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    ]
  },
  {
    id: 'prod-04',
    category_id: 'cat-05',
    category: INITIAL_CATEGORIES[4],
    name: 'Gorra Signature Prestige',
    slug: 'gorra-signature-prestige',
    sku: 'PR-AC001',
    short_description: 'Gorra bordada de 6 paneles en algodón gabardina con broche de hebilla metálica.',
    description: 'Diseño minimalista con bordado 3D de alta densidad del monograma PRESTIGE. Correa ajustable de cuero vegetal y visera semi-curva de estructura rígida.',
    price: 59900,
    compare_at_price: 75000,
    currency: 'COP',
    badge: 'OFERTA',
    is_active: true,
    is_featured: false,
    sort_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: 'img-04-1',
        product_id: 'prod-04',
        image_url: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=800&q=80',
        alt_text: 'Gorra Signature Prestige',
        sort_order: 1,
        is_primary: true,
        created_at: new Date().toISOString(),
      }
    ],
    variants: [
      { id: 'v-04-1', product_id: 'prod-04', color_name: 'Negro Matte', color_hex: '#111111', size: 'Única', stock: 15, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { id: 'v-04-2', product_id: 'prod-04', color_name: 'Beige Arena', color_hex: '#D9C8A9', size: 'Única', stock: 8, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    ]
  },
  {
    id: 'prod-05',
    category_id: 'cat-03',
    category: INITIAL_CATEGORIES[2],
    name: 'Chaqueta Bomber Urban Lux',
    slug: 'chaqueta-bomber-urban-lux',
    sku: 'PR-JK001',
    short_description: 'Chaqueta estilo bomber acolchada con acabado satinado repelente al agua y forro térmico.',
    description: 'Chaqueta outerwear de corte contemporáneo con cremallera dorada champán y tirador con sello grabado. Bolsillo en manga izquierda y puños elásticos acanalados.',
    price: 289900,
    compare_at_price: 320000,
    currency: 'COP',
    badge: 'EDICIÓN LIMITADA',
    is_active: true,
    is_featured: true,
    sort_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: 'img-05-1',
        product_id: 'prod-05',
        image_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
        alt_text: 'Chaqueta Bomber Urban Lux',
        sort_order: 1,
        is_primary: true,
        created_at: new Date().toISOString(),
      }
    ],
    variants: [
      { id: 'v-05-1', product_id: 'prod-05', color_name: 'Negro Ópalo', color_hex: '#111111', size: 'M', stock: 4, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { id: 'v-05-2', product_id: 'prod-05', color_name: 'Negro Ópalo', color_hex: '#111111', size: 'L', stock: 6, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { id: 'v-05-3', product_id: 'prod-05', color_name: 'Kaki Militar', color_hex: '#786D5F', size: 'XL', stock: 2, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    ]
  },
  {
    id: 'prod-06',
    category_id: 'cat-04',
    category: INITIAL_CATEGORIES[3],
    name: 'Jogger Heavy Fleece Charcoal',
    slug: 'jogger-heavy-fleece-charcoal',
    sku: 'PR-JG001',
    short_description: 'Jogger de algodón térmico de 380g con pretina elástica y cordon con puntas metálicas.',
    description: 'Combina la máxima libertad de movimiento con la estructura de un pantalón de vestir moderno. Bolsillos laterales con cierre invisible y bolsillo trasero con bordado.',
    price: 139900,
    compare_at_price: null,
    currency: 'COP',
    badge: null,
    is_active: true,
    is_featured: false,
    sort_order: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: 'img-06-1',
        product_id: 'prod-06',
        image_url: 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=800&q=80',
        alt_text: 'Jogger Heavy Fleece Charcoal',
        sort_order: 1,
        is_primary: true,
        created_at: new Date().toISOString(),
      }
    ],
    variants: [
      { id: 'v-06-1', product_id: 'prod-06', color_name: 'Grafito', color_hex: '#2B2B2B', size: 'S', stock: 5, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { id: 'v-06-2', product_id: 'prod-06', color_name: 'Grafito', color_hex: '#2B2B2B', size: 'M', stock: 9, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { id: 'v-06-3', product_id: 'prod-06', color_name: 'Grafito', color_hex: '#2B2B2B', size: 'L', stock: 7, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    ]
  },
  {
    id: 'prod-07',
    category_id: 'cat-01',
    category: INITIAL_CATEGORIES[0],
    name: 'Camiseta Oversize Cream Gold',
    slug: 'camiseta-oversize-cream-gold',
    sku: 'PR-TS002',
    short_description: 'Camiseta en tono crema marfil con estampado minimalista en serigrafía dorada.',
    description: 'Confeccionada en algodón orgánico peinado de tacto suave. Detalle del monograma PRESTIGE en el pecho y grabado del slogan en la espalda.',
    price: 89900,
    compare_at_price: 110000,
    currency: 'COP',
    badge: 'NUEVO',
    is_active: true,
    is_featured: false,
    sort_order: 7,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: 'img-07-1',
        product_id: 'prod-07',
        image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
        alt_text: 'Camiseta Oversize Cream Gold',
        sort_order: 1,
        is_primary: true,
        created_at: new Date().toISOString(),
      }
    ],
    variants: [
      { id: 'v-07-1', product_id: 'prod-07', color_name: 'Crema Marfil', color_hex: '#F2EFE9', size: 'S', stock: 6, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { id: 'v-07-2', product_id: 'prod-07', color_name: 'Crema Marfil', color_hex: '#F2EFE9', size: 'M', stock: 10, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { id: 'v-07-3', product_id: 'prod-07', color_name: 'Crema Marfil', color_hex: '#F2EFE9', size: 'L', stock: 4, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    ]
  },
  {
    id: 'prod-08',
    category_id: 'cat-02',
    category: INITIAL_CATEGORIES[1],
    name: 'Hoodie Boxy Fit Champagne',
    slug: 'hoodie-boxy-fit-champagne',
    sku: 'PR-H002',
    short_description: 'Hoodie de silueta cuadrada boxy fit con detalles de costuras expuestas y tono exclusivo.',
    description: 'Una pieza de alta costura streetwear en color champagne sobrio. Hombros notoriamente caídos y longitud recortada limpia a la cintura.',
    price: 179900,
    compare_at_price: null,
    currency: 'COP',
    badge: 'EDICIÓN LIMITADA',
    is_active: true,
    is_featured: false,
    sort_order: 8,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: 'img-08-1',
        product_id: 'prod-08',
        image_url: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=800&q=80',
        alt_text: 'Hoodie Boxy Fit Champagne',
        sort_order: 1,
        is_primary: true,
        created_at: new Date().toISOString(),
      }
    ],
    variants: [
      { id: 'v-08-1', product_id: 'prod-08', color_name: 'Champagne', color_hex: '#E6D19A', size: 'S', stock: 3, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { id: 'v-08-2', product_id: 'prod-08', color_name: 'Champagne', color_hex: '#E6D19A', size: 'M', stock: 5, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { id: 'v-08-3', product_id: 'prod-08', color_name: 'Champagne', color_hex: '#E6D19A', size: 'L', stock: 2, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    ]
  },
  {
    id: 'prod-09',
    category_id: 'cat-04',
    category: INITIAL_CATEGORIES[3],
    name: 'Pantalón Cargo Tactical Black',
    slug: 'pantalon-cargo-tactical-black',
    sku: 'PR-CG002',
    short_description: 'Cargo táctico en gabardina de algodón saturado con reata ajustable incorporada.',
    description: 'Pantalón de corte funcional con 8 bolsillos, rodillas articuladas y cinta técnica con cierre de liberación rápida en cinturón.',
    price: 169900,
    compare_at_price: 199900,
    currency: 'COP',
    badge: 'OFERTA',
    is_active: true,
    is_featured: false,
    sort_order: 9,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: 'img-09-1',
        product_id: 'prod-09',
        image_url: 'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?auto=format&fit=crop&w=800&q=80',
        alt_text: 'Pantalón Cargo Tactical Black',
        sort_order: 1,
        is_primary: true,
        created_at: new Date().toISOString(),
      }
    ],
    variants: [
      { id: 'v-09-1', product_id: 'prod-09', color_name: 'Negro Táctico', color_hex: '#111111', size: '30', stock: 4, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { id: 'v-09-2', product_id: 'prod-09', color_name: 'Negro Táctico', color_hex: '#111111', size: '32', stock: 6, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { id: 'v-09-3', product_id: 'prod-09', color_name: 'Negro Táctico', color_hex: '#111111', size: '34', stock: 7, is_available: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    ]
  },
];

// Generar páginas de exactamente 3 productos por página
export const INITIAL_PAGES: CatalogPageWithProducts[] = [
  {
    id: 'page-01',
    page_number: 1,
    title: 'ELEGANCIA URBANA',
    subtitle: 'Clásicos renovados para un estilo limpio, seguro y auténtico.',
    layout_type: 'three-products',
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    products: [INITIAL_PRODUCTS[0], INITIAL_PRODUCTS[1], INITIAL_PRODUCTS[2]],
  },
  {
    id: 'page-02',
    page_number: 2,
    title: 'VIBRAS DE VERANO & OUTWEAR',
    subtitle: 'Prendas ligeras, colores frescos y energía para destacar.',
    layout_type: 'three-products',
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    products: [INITIAL_PRODUCTS[3], INITIAL_PRODUCTS[4], INITIAL_PRODUCTS[5]],
  },
  {
    id: 'page-03',
    page_number: 3,
    title: 'CHICO URBANO — EDICIÓN EXCLUSIVA',
    subtitle: 'Básicos con actitud para llevar tu estilo a donde quieras.',
    layout_type: 'three-products',
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    products: [INITIAL_PRODUCTS[6], INITIAL_PRODUCTS[7], INITIAL_PRODUCTS[8]],
  },
];
